# Generated by Django 5.1.7 on 2025-03-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='authors_profiles'),
        ),
    ]
